name: Executar programa de temperatures

on:
  schedule:
    - cron: '24 4 * * *'  # Cada dia a les 23:59 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instal·lar dependències
        run: pip install -r requirements.txt

      - name: Executar script Python
        run: python time.py

      - name: Confirmar i fer commit del nou fitxer
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add temp_*.json
          git commit -m "Afegit fitxer JSON amb temperatures del dia" || echo "Sense canvis"
          git push